
services:
  web:
    container_name: flask-app
    image: my-flask-app:multistage
    ports:
      - "5002:5002"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-net

  db:
    container_name: mysql-db
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-net

volumes:
  mysql_data:

networks:
  app-net:
    driver: bridge
